# Generated by Django 4.0.6 on 2022-10-22 13:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_video_facultyinstructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description2',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Student Instructions'),
        ),
        migrations.AlterField(
            model_name='video',
            name='facultyInstructions',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Faculty Instructions'),
        ),
    ]
